name: Builds and releases the mod

on:
  workflow_dispatch

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - version: 1.16.5
            branch: master
            jdk: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    
    - name: Extract version
      run: sed -n '/^mod_version=/p' gradle.properties >> $GITHUB_ENV
      
    - name: Print version
      run: echo "Mod Version=${{ env.mod_version }}"
      
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ matrix.version }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-${{ matrix.version }}
    
    - name: Run datagen
      run: ./gradlew runData
      continue-on-error: true
      
    - name: Remove .cache folder
      run: rm -rf src/generated/resources/.cache
    
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/libs/*.jar
    
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ matrix.version }}-${{ env.mod_version }}"
        prerelease: false
        title: "VoodooMod ${{ matrix.version }}-${{ env.mod_version }}"
        files: |
          LICENSE
          build/libs/*.jar

